# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PercyUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import iconify as ico



class Ui_Percy(object):
    def setupUi(self, Percy):
        Percy.setObjectName("Percy")
        Percy.resize(850, 650)
        self.centralwidget = QtWidgets.QWidget(Percy)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 850, 650))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("C:\\Users\\aryan\\Downloads\\percy2.gif"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(750, 20, 60, 50))
        #icon = ico.Icon('feather:mic')
        #self.pushButton.setIcon(icon)
        self.pushButton.setStyleSheet("background-image : url(mic2.png);")
        self.pushButton.setText("Start")
        #self.pushButton.setFont(Qfont('Times',20))
        self.pushButton.setObjectName("pushButton")
        Percy.setCentralWidget(self.centralwidget)
        self.retranslateUi(Percy)
        QtCore.QMetaObject.connectSlotsByName(Percy)

    def retranslateUi(self, Percy):
        _translate = QtCore.QCoreApplication.translate
        Percy.setWindowTitle(_translate("Percy", "Percy"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Percy = QtWidgets.QMainWindow()
    ui = Ui_Percy()
    ui.setupUi(Percy)
    Percy.show()
    sys.exit(app.exec_())
