# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PercyUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
# from tkinter import *
# root=Tk()
# root.title("Percy")
# root.overrideredirect(True)
# root.geometry("650x550")
# def moveApp(e):
#     root.geometry(f'+{e.x_root}+{e.y_root}')

class Ui_Percy(object):
    def setupUi(self, Percy):
        Percy.setObjectName("Percy")
        Percy.resize(750, 550)
        # titlebar=Frame(root,bg="black",relief="raised")
        # titlebar.pack(expand=1,fill=X)
        # titlebar.bind("<B1-Motion>", moveApp)
        # titleLabel=Label(titlebar, text="  Percy",bg="black",fg='white')
        # titleLabel.pack(side=LEFT,pady=6)
        self.centralwidget = QtWidgets.QWidget(Percy)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 750, 551))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("C:\\Users\\aryan\\Downloads\\percy4.gif"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(650,30, 71, 71))
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:\\Users\\aryan\\Downloads\\mic2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(115, 115))
        self.pushButton.setObjectName("pushButton")
        Percy.setCentralWidget(self.centralwidget)

        self.retranslateUi(Percy)
        QtCore.QMetaObject.connectSlotsByName(Percy)

    def retranslateUi(self, Percy):
        _translate = QtCore.QCoreApplication.translate
        Percy.setWindowTitle(_translate("Percy", "Percy"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Percy = QtWidgets.QMainWindow()
    ui = Ui_Percy()
    ui.setupUi(Percy)
    Percy.show()
    sys.exit(app.exec_())
